"""The compact per-case TRACE = the web-replay artifact. Part of CONTRACT 2: its shape is mirrored by
frontend/src/lib/contract.types.ts, so a drift fails the web build. Each trace is built deterministically from the
REAL committed learned-tier outputs (rv-cwru-samples.json, rv-learned-metrics.json, cwru-benchmark.json) — it
references the shared held-out segments by class instead of copying raw arrays, so every trace stays tiny. The
synthetic + prognostics traces are generated by a seeded RNG and clearly flagged synthetic.
"""
from __future__ import annotations

from typing import Any

import numpy as np

from .rng import make_rng

TRACE_SCHEMA = "rotorvitals.trace/v1"
NOMINAL_FR = 1730.0 / 60.0   # shaft rate (Hz) at the held-out 3 HP load
RUL_STEPS = 60               # decimated synthetic run-to-failure horizon


def _diagnosis(case: Any, samples: dict, metrics: dict) -> dict:
    classes = metrics["wdcnn"]["classes"]
    ci = classes.index(case.fault_type)
    size_in = case.params.get("sizeIn")
    if size_in is not None:
        # T4 cross-severity case (unseen 0.014"/0.021" fault size): its REAL segments carry this case's id, and the
        # WDCNN recall is the held-out severity recall (trained on 0.007"), not the in-size held-out-load recall.
        seg_idx = [i for i, s in enumerate(samples["samples"]) if s.get("caseId") == case.id]
        row = next((r for r in metrics.get("crossSeverity", {}).get("rows", [])
                    if r["fault"] == case.fault_type and abs(r["sizeIn"] - size_in) < 1e-6), None)
        recall = row["wdcnn"] if row else None
        conf_row = [int(row["wdcnnDist"].get(c, 0)) for c in classes] if row else metrics["wdcnn"]["confusion"][ci]
    else:
        # the original held-out-3HP 0.007" cases — exclude the cross-severity segments that share the class.
        seg_idx = [i for i, s in enumerate(samples["samples"])
                   if s["cls"] == case.fault_type and not s.get("caseId")]
        recall = metrics["wdcnn"]["perClass"].get(case.fault_type)
        conf_row = metrics["wdcnn"]["confusion"][ci]
    return {
        "classes": classes,
        "fault_type": case.fault_type,
        "segment_refs": seg_idx,                       # indices into rv-cwru-samples.json (no raw copy)
        "n_segments": len(seg_idx),
        "wdcnn": {
            "per_class_recall": recall,
            "confusion_row": conf_row,
            "accuracy": metrics["wdcnn"]["accuracy"],
        },
        "deep_ae": {
            "threshold_p99": metrics["deepAE"]["thresholdP99"],
            "fault_vs_healthy_auc": metrics["deepAE"].get("faultVsHealthyAUC"),
            "healthy_false_flag_rate": metrics["deepAE"].get("healthyFalseFlagRate"),
        },
    }


def _robustness(metrics: dict) -> dict:
    return {"snr_curve": metrics["wdcnn"]["snrCurve"]}


def _classical(case: Any, benchmark: dict) -> dict:
    m = benchmark["methods"][case.params["method"]]
    return {
        "method": case.params["method"],
        "confusion": m["confusion"],
        "row_recall": m["rowRecall"],
        "accuracy": m["accuracy"],
        "n": m["n"],
        "classes": benchmark["classes"],
    }


def _synthetic(case: Any) -> dict:
    planted = case.params.get("planted")
    defect_hz = round(planted * NOMINAL_FR, 3) if planted else None
    return {"fault_type": case.fault_type, "planted_mult": planted, "fr_hz": round(NOMINAL_FR, 3),
            "defect_hz": defect_hz}


def _prognostics(case: Any, seed: int) -> dict:
    """A seeded synthetic run-to-failure HEALTH-INDICATOR trend + a 1/HI-slope RUL projection. Labelled synthetic
    (the XJTU-SY/MFPT real run-to-failure datasets are roadmap, documented in docs/cases/)."""
    rng = make_rng(seed)
    onset = float(case.params["onset"])
    t = np.linspace(0.0, 1.0, RUL_STEPS)
    base = 0.05 + 0.02 * rng.standard_normal(RUL_STEPS) * 0.0   # deterministic baseline
    rise = np.where(t >= onset, np.expm1(4.0 * (t - onset)) / np.expm1(4.0 * (1.0 - onset)), 0.0)
    hi = np.clip(base + rise + 0.01 * rng.standard_normal(RUL_STEPS), 0.0, None)
    # RUL projection from the last third: linear fit of HI vs t, extrapolate to HI=1.0 (failure threshold)
    k = max(2, RUL_STEPS // 3)
    a, b = np.polyfit(t[-k:], hi[-k:], 1)
    t_fail = (1.0 - b) / a if a > 1e-9 else 1.0
    return {
        "fault_type": case.fault_type, "onset": onset,
        "t": [round(float(v), 4) for v in t],
        "hi": [round(float(v), 4) for v in hi],
        "rul_est_norm": round(float(max(0.0, t_fail - t[-1])), 4),
        "t_fail_est": round(float(min(2.0, t_fail)), 4),
        "true_fail_norm": 1.0,
    }


def build_trace(case: Any, *, samples: dict, metrics: dict, benchmark: dict, seed: int) -> dict:
    if case.kind == "diagnosis":
        payload = _diagnosis(case, samples, metrics)
    elif case.kind == "robustness":
        payload = _robustness(metrics)
    elif case.kind == "classical":
        payload = _classical(case, benchmark)
    elif case.kind == "synthetic":
        payload = _synthetic(case)
    elif case.kind == "prognostics":
        payload = _prognostics(case, seed)
    else:
        raise ValueError(f"unknown case kind: {case.kind!r}")
    return {
        "schema": TRACE_SCHEMA,
        "case_id": case.id,
        "category": case.category,
        "kind": case.kind,
        "real_or_synthetic": case.real_or_synthetic,
        "expected_band": case.expected_band,
        "payload": payload,
    }
